version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ADMIN123
      POSTGRES_DB: CRUD
    networks:
      - CRUDTEST
  test-db:
    image: postgres:13
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ADMIN123
      POSTGRES_DB: CRUD
    networks:
      - CRUDTEST
networks:
  CRUDTEST:


